# Generated by Django 5.1.3 on 2026-03-07 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ActivityParticipationManagementSystem', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activityparticipant',
            old_name='activity_id',
            new_name='activity',
        ),
        migrations.RenameField(
            model_name='activityparticipant',
            old_name='userstudent_id',
            new_name='user_student',
        ),
        migrations.RenameField(
            model_name='activitypdf',
            old_name='activity_id',
            new_name='activity',
        ),
        migrations.RenameField(
            model_name='activitytimeevent',
            old_name='activity_id',
            new_name='activity',
        ),
    ]
