# Generated by Django 5.1.3 on 2026-03-07 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActivityParticipationManagementSystem', '0002_rename_activity_id_activityparticipant_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitypdf',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_files', to='ActivityParticipationManagementSystem.activity'),
        ),
    ]
