# Generated by Django 5.1.3 on 2026-03-07 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActivityParticipationManagementSystem', '0003_alter_activitypdf_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitypdf',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ActivityPdf', to='ActivityParticipationManagementSystem.activity'),
        ),
    ]
