# Generated by Django 5.1.3 on 2026-03-04 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentyearlyactivitycredit',
            old_name='avail1',
            new_name='earned_credits_category_1',
        ),
        migrations.RenameField(
            model_name='studentyearlyactivitycredit',
            old_name='avail2',
            new_name='earned_credits_category_2',
        ),
        migrations.RenameField(
            model_name='studentyearlyactivitycredit',
            old_name='avail3',
            new_name='earned_credits_category_3',
        ),
        migrations.RenameField(
            model_name='studentyearlyactivitycredit',
            old_name='avail4',
            new_name='earned_credits_category_4',
        ),
        migrations.RenameField(
            model_name='studentyearlyactivitycredit',
            old_name='avail5',
            new_name='earned_credits_category_5',
        ),
        migrations.RenameField(
            model_name='studentyearlyactivitycredit',
            old_name='avail6',
            new_name='earned_credits_category_6',
        ),
        migrations.RenameField(
            model_name='studentyearlyactivitycredit',
            old_name='req1',
            new_name='required_credits_category_1',
        ),
        migrations.RenameField(
            model_name='studentyearlyactivitycredit',
            old_name='req2',
            new_name='required_credits_category_2',
        ),
        migrations.RenameField(
            model_name='studentyearlyactivitycredit',
            old_name='req3',
            new_name='required_credits_category_3',
        ),
        migrations.RenameField(
            model_name='studentyearlyactivitycredit',
            old_name='req4',
            new_name='required_credits_category_4',
        ),
        migrations.RenameField(
            model_name='studentyearlyactivitycredit',
            old_name='req5',
            new_name='required_credits_category_5',
        ),
        migrations.RenameField(
            model_name='studentyearlyactivitycredit',
            old_name='req6',
            new_name='required_credits_category_6',
        ),
        migrations.RenameField(
            model_name='userstudent',
            old_name='type_Scholarship_or_Student_loan_fund',
            new_name='type_scholarship',
        ),
        migrations.AlterField(
            model_name='studentyearlyactivitycredit',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StudentYearlyActivityCredit', to='Accounts.userstudent'),
        ),
        migrations.AlterField(
            model_name='userfacultystaff',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserFacultyStaff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userresponsible',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserResponsible', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userstudent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserStudent', to=settings.AUTH_USER_MODEL),
        ),
    ]
